-- =============================================
-- Author: Bob Wakefield
-- Create date: 13Oct17
-- Description: clean price data
-- Change Log:
-- 15Oct20 Created doc bloc sample. - BW
-- =============================================